(function ($) {
$.Redactor.opts.langs['cs'] = {
	html: 'Zdroj',
	video: 'Video',
	image: 'Obrázek',
	table: 'Tabulka',
	link: 'Odkaz',
	link_insert: 'Vložit odkaz ...',
	link_edit: 'Upravit odkaz',
	unlink: 'Odstranit odkaz',
	formatting: 'Styl',
	paragraph: 'Prostý text',
	quote: 'Citace',
	code: 'Zdrojový kód',
	header1: 'Nadpis 1',
	header2: 'Nadpis 2',
	header3: 'Nadpis 3',
	header4: 'Nadpis 4',
	header5: 'Nadpis 5',
	bold:  'Tučně',
	italic: 'Kurzíva',
	fontcolor: 'Barva textu',
	backcolor: 'Barva pozadí',
	unorderedlist: 'Odrážky',
	orderedlist: 'Číslování',
	outdent: 'Zmenšit odsazení',
	indent: 'Zvětšit odsazení',
	cancel: 'Storno',
	insert: 'Vložit',
	save: 'Uložit',
	_delete: 'Odstranit',
	insert_table: 'Vložit tabulku',
	insert_row_above: 'Vložit řádek před',
	insert_row_below: 'Vložit řádek za',
	insert_column_left: 'Vložit sloupec vlevo',
	insert_column_right: 'Vložit sloupec vpravo',
	delete_column: 'Odstranit sloupec',
	delete_row: 'Odstranit řádek',
	delete_table: 'Odstranit tabulku',
	rows: 'Řádky',
	columns: 'Sloupce',
	add_head: 'Vložit záhlaví',
	delete_head: 'Odstranit záhlaví',
	title: 'Nadpis',
	image_position: 'Umístění obrázku',
	none: 'Žádné',
	left: 'Doleva',
	right: 'Doprava',
	image_web_link: 'nebo odkaz na obrázek',
	text: 'Text',
	mailto: 'Pošta e-mail',
	web: 'URL',
	video_html_code: 'Zdrojový kód souboru videa',
	file: 'Soubor',
	upload: 'Nahrát na server',
	download: 'Stáhnout',
	choose: 'Vybrat ze seznamu',
	or_choose: 'nebo vyberte',
	drop_file_here: 'Přesunout soubor sem',
	align_left:	'Zarovnat doleva',
	align_center: 'Zarovnat na střed',
	align_right: 'Zarovnat doprava',
	align_justify: 'Vyrovnat',
	horizontalrule: 'Vodorovná linka',
	fullscreen: 'Celá obrazovka',
	deleted: 'Přeškrtnutí',
    anchor: 'Kotva',
	link_new_tab: 'Otevřít odkaz v novém okně',
	underline: 'Podtržení',
	alignment: 'Zarovnání',
	filename: 'Název (volitelně)',
	edit: 'Upravit',
	center: 'Na střed'
};
})(jQuery);